### PR TITLE
Moved the API key setting to a device setting

### PR DESCRIPTION
**Pull request by omelhus**
Hey,

I've moved the API key setting into a setting on the device instead.

### CODE REVIEW

**Comment by omelhus** [comment]
I've made some changes to the main SmartApp as well, so now you don't have to install it in a simulator in order to get you access token. Just install it and find the access token in the preferences for the app.

**Comment by kirotnes** [comment]
Hey @omelhus 

These changes look good and I would like to merge them. Currently, we don't have any dedicated Tibber-people maintaining this repo (@jsandv is sadly no longer with us) and we are a bit pressed for time right now with regards to other projects.

If we merge this would you be interested in following up on any issues that might arise?

**Comment by omelhus** [comment]
I'll try to follow up on issues here. This is a spare time thing for me, so I cannot promise anything in regards of response time.

**Comment by kirotnes** [comment]
Totally get that of course. 

Really cool to get community participation - thanks!

**Comment by omelhus** [comment]
Cheers! 

I'll try to update the screenshots later (and fix the reference to the wrong list item in the readme).

**Pull request merged**
